{% set name = "efm-langserver" %}
{% set version = "0.0.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mattn/efm-langserver/archive/v{{ version }}.tar.gz
  sha256: 4149b2922899ce313a89f60851f6678369253ed542dd65bdc8dd22f3cf1629bb

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - efm-langserver --help

about:
  home: https://github.com/mattn/efm-langserver
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: General purpose Language Server
  dev_url: https://github.com/mattn/efm-langserver

extra:
  recipe-maintainers:
    - danielnachun
