schema_version: 1

context:
  version: "0.0.55"

package:
  name: efm-langserver
  version: ${{ version }}

source:
  url: https://github.com/mattn/efm-langserver/archive/v${{ version }}.tar.gz
  sha256: 3e46b2e95725dc0e85816c6c6811cb81ab573147df0e888bb3354642e1286e9f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - efm-langserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: General purpose Language Server
  homepage: https://github.com/mattn/efm-langserver
  repository: https://github.com/mattn/efm-langserver

extra:
  recipe-maintainers:
    - danielnachun
