schema_version: 1

context:
  version: "0.0.56"

package:
  name: efm-langserver
  version: ${{ version }}

source:
  url: https://github.com/mattn/efm-langserver/archive/v${{ version }}.tar.gz
  sha256: 6b2c44c904a0a3c54909688ccebc8ca32bba319abbd7f6a8a26590a6359e4950

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - efm-langserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: General purpose Language Server
  homepage: https://github.com/mattn/efm-langserver
  repository: https://github.com/mattn/efm-langserver

extra:
  recipe-maintainers:
    - danielnachun
